use project1



--select top 10 * from customer 
select top 10 * from customer
--very common to see demographics 
--total revenue generated by male vs female
select gender,sum(purchase_amount) as revenue
from customer
group by gender


-- which customers used a discount but still spent more than average purchase amount
select customer_id,purchase_amount
from customer
where discount_applied='Yes' and purchase_amount>(SELECT AVG(purchase_amount) FROM customer)



--top 5 products with highest average review rating

select top 5 item_purchased,round(AVG(review_rating),2)
from customer
group by item_purchased
order by avg(review_rating) desc

--compare average purchase amount by standard and express shipping method
select shipping_type,AVG(purchase_amount)
from customer
where shipping_type in ('Standard','Express')
group by shipping_type

--do subscribed customers spend more. compare avg spend and revenue b/w subscribers and non-subscribers
select subscription_status,count(customer_id)as total_customers,round(avg(purchase_amount),2) as avg_spend,round(sum(purchase_amount),2) as total_revenue
from customer
group by subscription_status

--which 5 products have highest amount of purchases with discount applied
select top 5 item_purchased,
round(100*sum(case when discount_applied='Yes' then 1 else 0 end)/count(*),2) as discount_rate
from customer
group by item_purchased
order by discount_rate desc


-- segment customers into new,returning and loyal customers based on previous purchases and
-- show count of each segment

with customer_type as (
    select
        customer_id,
        previous_purchases,
        case
            when previous_purchases = 1 then 'New'
            when previous_purchases between 2 and 10 then 'Returning'
            else 'Loyal'
        end as customer_segment
    from customer
)
select customer_segment, count(customer_segment) as count_customers
from customer_type
group by customer_segment

-- what are the top three most purchased products in each category
WITH item_count AS (
    SELECT
        category,
        item_purchased,
        COUNT(customer_id)  AS total_orders,
        ROW_NUMBER()  OVER (
            PARTITION BY category
            ORDER BY COUNT(customer_id) DESC
        )                   AS item_rank
    FROM customer
    GROUP BY category, item_purchased
)
select * from item_count
where item_rank <=3

-- are customers who are repeat buyers likely to subscribe
select subscription_status,
count(customer_id) as repeat_buyers
from customer
where purchase_amount>5
group by subscription_status

-- revenue distribution of each age group
select [Age Group],sum(purchase_amount) as revenue
from customer
group by [Age Group]
